---
configure_explorer: true
configure_hostname: true
#custom_hostname: windows-ansible
configure_start_menu: true
configure_taskbar: true
disable_mouse_acceleration: true
remote_desktop_enabled: true
remove_desktop_icons: true
set_sound_scheme: true

install_windows_updates: true
windows_updates_reboot: true
update_categories:
  # You can install only specific updates by uncommenting it
  # * - installs all updates
  # - "*"
  #- Critical Updates
  # - Definition Updates
  # - Developer Kits
  # - Feature Packs
  #- Security Updates
  # - Service Packs
  # - Tools
  #- Update Rollups
  # - Updates
  # - Upgrades

change_power_plan: true
# high_performance
# balanced
# power_saver
power_plan: "high_performance"

install_chocolatey_packages: true
choco_installed_packages:
  # installs 2019.2.2.20191 version of the adobe reader
  - name: adobereader
    version: "2022.002.20191"
  # installs latest version of the Firefox while ignoring the package checksum
  - name: Firefox
    state: latest
    choco_args: --ignorechecksum
  # installs awscli, but won't update it
  #- awscli
  #- Firefox
  #- git
  #- golang
  #- jre8
  #- kubernetes-cli
  #- microsoft-windows-terminal
  #- peazip
  #- powertoys
  #- python3
  #- sharex
  #- telegram
  #- terraform
  #- vlc
  #- vscode
  #- zoom

install_winget_packages: true
winget_packages:
  # - name: "Auto Dark Mode"
  #   source: winget
  - name: WinDynamicDesktop
    source: winget

install_fonts: true
installed_nerdfonts:
  - FiraCode
  - FantasqueSansMono

install_ohmyposh: true

# List of features: "Get-WindowsOptionalFeature -Online"
install_windows_features: false
windows_features:
  Microsoft-Hyper-V: true

# List of valid distributions that can be installed:
# wsl-alpine
# wsl-archlinux
# wsl-debiangnulinux
# wsl-fedoraremix
# wsl-kalilinux
# wsl-opensuse
# wsl-sles
# wsl-ubuntu-1604
# wsl-ubuntu-1804
# wsl-ubuntu-2004
install_wsl2: false
wsl2_distribution: wsl-ubuntu-2004

remove_bloatware: true
bloatware:
  - Microsoft.BingNews
  - Microsoft.BingWeather
  - Microsoft.GamingApp
  - Microsoft.GetHelp
  - Microsoft.Getstarted
  # - Microsoft.Messaging
  - Microsoft.Microsoft3DViewer
  - Microsoft.MicrosoftOfficeHub
  - Microsoft.MicrosoftSolitaireCollection
  - Microsoft.MicrosoftStickyNotes
  - Microsoft.MixedReality.Portal
  # - Microsoft.MSPaint
  - Microsoft.Office.OneNote
  - Microsoft.OneConnect
  - Microsoft.People
  - Microsoft.PowerAutomateDesktop
  - Microsoft.Print3D
  - Microsoft.ScreenSketch
  - Microsoft.SkypeApp
  - Microsoft.Todos
  - Microsoft.Windows.Photos
  - Microsoft.WindowsAlarms
  # - Microsoft.WindowsCalculator
  - Microsoft.Wallet
  - Microsoft.WindowsCamera
  # - microsoft.windowscommunicationsapps
  - Microsoft.WindowsFeedbackHub
  - Microsoft.WindowsMaps
  - Microsoft.WindowsSoundRecorder
  - Microsoft.Xbox
  - Microsoft.Xbox.TCUI
  - Microsoft.XboxApp
  - Microsoft.XboxGameOverlay
  - Microsoft.XboxSpeechToTextOverlay
  # - Microsoft.YourPhone
  - Microsoft.ZuneMusic
  - Microsoft.ZuneVideo
  - MicrosoftTeams
  - TikTok
  - ESPN

configure_storage_sense: true
storage_sense:
  enabled: true
  run_frequency: 1
  delete_unused_files: true
  delete_recycle_bin_files: true
  recycle_bin_age: 14
  delete_downloads_files: true
  downloads_age: 14

defrag_volumes: false
include_volumes:


############################################################# Adding new account #############################################################

add_new_account: true

# List of all companies
# mall
# gbr
# pal
# gdc
# ambak
company: pal

# List of type of device
# DT
# LT
# SV
# POS
# MAC
device_type: DT

# Input new account info here
first_name: Mark
last_name: Angeles

# Do not edit this part
win_full_name: "{{ first_name }} {{ last_name }}"
grab_first_letter: "{{ last_name | regex_search('^[a-zA-Z]')}}"
win_user_name: "{{ first_name | lower }}{{ grab_first_letter | lower }}"
win_password: "P@ssw0rd01"
custom_hostname: "{{ device_type }}-{{ first_name }}{{ last_name }}"


##### Copy installers #####
copy_installers: false


##### Map Network Drive #####
map_drive: true
nas_ip: 192.168.1.10

##### Install remote management #####
install_rms: true


##### Install gdc-kyocera printer #####
install_kyocera: true

PrinterName: "gdc-kyocera"
PrinterPortName: "KyoceraM3645idn"
PrinterIP: "192.168.1.200"
PrintDriverName: "Kyocera ECOSYS M3645idn KX"



##### Adding nas account #####
add_nas_account: true




















